In [2]:
import numpy as np

In [3]:
a = np.arange(20)
b = a.reshape(4, 5)
c = np.copy(a)
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
# override
b[0, 0] = 753
print(b)

[[753   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [5]:
# Above modification affects even the contants of a.
print(a)

[753   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [6]:
print(c)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
