In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x1 = tf.placeholder(tf.float32, [None, 10])
x2 = tf.placeholder(tf.float32, [None, 10])
prod = x1 * x2  # product by elements
innprd = tf.reduce_sum(prod, reduction_indices=[1])
vectorsum =  tf.reduce_sum(prod, reduction_indices=[0])
dat1 = np.arange(20).reshape(2, 10)
dat2 = np.arange(10,30).reshape(2, 10)
print(dat1)
print(dat2)
with tf.Session() as sess:
    result = sess.run((prod, innprd, vectorsum),
                   feed_dict={x1: dat1, x2: dat2})
print(result[0])  # prod
print(result[1])  # innprd
print(result[2])  # vectorsum

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[   0.   11.   24.   39.   56.   75.   96.  119.  144.  171.]
 [ 200.  231.  264.  299.  336.  375.  416.  459.  504.  551.]]
[  735.  3635.]
[ 200.  242.  288.  338.  392.  450.  512.  578.  648.  722.]


In [3]:
matrix1 = tf.constant([[3., 3.]]) #1x2
matrix1_1 = tf.constant([3., 3.])
matrix2 = tf.constant([[2.],[2.]]) #2x1
product = tf.matmul(matrix1, matrix2)
# product_1 = tf.matmul(matrix1_1, matrix2)
# => incorrect about the shape (dimension)
matrix3 = tf.constant([[2]]) #1x1
matrix4 = tf.constant([[1, 2, 3]]) #1x3
product1 = tf.matmul(matrix3, matrix4)



In [4]:
state = tf.Variable(0, name="counter")
one = tf.constant(1)
new_value = tf.add(state, one)
# new_value = tf.sub(state, one)
update = tf.assign(state, new_value)

init_op = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


In [5]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.mul(input1, input2)
ar0 = np.arange(10)
ar1 = np.arange(10)
np.random.shuffle(ar0)
np.random.shuffle(ar1)

print(ar0)
print(ar1)

with tf.Session() as sess:
    result = sess.run([output], feed_dict = {input1:ar0, input2:ar1})

print(result)
print(np.sum(result))
    

[5 3 7 4 1 8 9 2 0 6]
[2 4 3 7 5 6 9 0 8 1]
[array([ 10.,  12.,  21.,  28.,   5.,  48.,  81.,   0.,   0.,   6.], dtype=float32)]
211.0


In [6]:
input5 = tf.placeholder(tf.float32)
sigmo = tf.sigmoid(input5)
ar2 = np.arange(-3, 3, 0.2)
print(ar2)
with tf.Session() as sess:
    print(sess.run([sigmo], feed_dict = {input5: ar2}))

[ -3.00000000e+00  -2.80000000e+00  -2.60000000e+00  -2.40000000e+00
  -2.20000000e+00  -2.00000000e+00  -1.80000000e+00  -1.60000000e+00
  -1.40000000e+00  -1.20000000e+00  -1.00000000e+00  -8.00000000e-01
  -6.00000000e-01  -4.00000000e-01  -2.00000000e-01   2.66453526e-15
   2.00000000e-01   4.00000000e-01   6.00000000e-01   8.00000000e-01
   1.00000000e+00   1.20000000e+00   1.40000000e+00   1.60000000e+00
   1.80000000e+00   2.00000000e+00   2.20000000e+00   2.40000000e+00
   2.60000000e+00   2.80000000e+00]
[array([ 0.04742587,  0.05732417,  0.06913843,  0.08317269,  0.09975048,
        0.11920292,  0.14185107,  0.16798161,  0.1978161 ,  0.23147522,
        0.26894143,  0.31002551,  0.35434371,  0.40131235,  0.45016602,
        0.5       ,  0.54983395,  0.59868765,  0.64565629,  0.68997449,
        0.7310586 ,  0.76852483,  0.80218393,  0.83201838,  0.85814887,
        0.88079703,  0.90024954,  0.91682732,  0.93086159,  0.94267583], dtype=float32)]
