In [1]:
import tensorflow as tf

In [2]:
three = tf.constant(3.)

with tf.Session() as sess:
    print(sess.run(three))

3.0


In [3]:
matrix1 = tf.constant([[3., 3.]])

matrix2 = tf.constant([[2.], [2.]])

product = tf.matmul(matrix1, matrix2)

with tf.Session() as sess:
    print(sess.run(product))


[[ 12.]]


In [4]:
import numpy as np

arr0 = [1, 3, 5]
arr1 = np.array([1, 3, 5])
arr1_1 = np.array(arr0)
print(type(arr0))
print(type(arr1))
print(type(arr1_1))

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
arr2 = np.arange(20)
print(arr2)

arr3 = arr2.reshape(4, 5)
print(arr3)
print(arr3.shape)
print(arr2.shape)
print(arr3.ndim)
print(arr2.ndim)

arr4 = np.random.randint(10, size=6)
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(20,)
2
1
[5 3 9 7 2 8]


In [6]:
from numpy.random import randint

arr5 = randint(10, size=(3, 5))
print(arr5)

print(arr5 * 3)
print(arr5 + 1)

arr6 = randint(10, size=(3, 5))
print(arr6)

print(arr5 + arr6)
print(arr5 * arr6)


def sq(x):
    return(x * x)

print(arr5)
print(sq(arr5))

[[4 2 5 3 0]
 [5 0 5 2 0]
 [4 8 0 7 2]]
[[12  6 15  9  0]
 [15  0 15  6  0]
 [12 24  0 21  6]]
[[5 3 6 4 1]
 [6 1 6 3 1]
 [5 9 1 8 3]]
[[8 4 5 2 7]
 [3 7 4 6 1]
 [2 5 8 0 5]]
[[12  6 10  5  7]
 [ 8  7  9  8  1]
 [ 6 13  8  7  7]]
[[32  8 25  6  0]
 [15  0 20 12  0]
 [ 8 40  0  0 10]]
[[4 2 5 3 0]
 [5 0 5 2 0]
 [4 8 0 7 2]]
[[16  4 25  9  0]
 [25  0 25  4  0]
 [16 64  0 49  4]]


In [7]:
print(np.random.randn(10))

from numpy.random import randn

arr7 = randn(5)
print(arr7)

arr8 = randint(10, size=5)
print(arr8)

print(arr7.dtype)
print(arr8.dtype)

[-0.67852307 -0.79438437  0.4955403   0.75803833 -0.36254698  0.84734273
  1.12809585  0.78500713 -0.15220105 -1.26818212]
[-0.80455239 -0.53190621  0.73965068 -1.07219426 -2.47496091]
[5 2 4 5 9]
float64
int64


In [8]:
print(np.zeros(10))
print(np.zeros((3, 5)))
print(np.ones(10))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [9]:
arr9 = randint(10, size=20)
print(arr9)

print(arr9[0])
print(arr9[3])
print(arr9[1:5])
print(arr9[1:])
print(arr9[:])

[9 6 7 0 5 6 3 3 1 5 0 3 5 8 1 3 6 9 9 4]
9
0
[6 7 0 5]
[6 7 0 5 6 3 3 1 5 0 3 5 8 1 3 6 9 9 4]
[9 6 7 0 5 6 3 3 1 5 0 3 5 8 1 3 6 9 9 4]


In [10]:
arr10 = arr9.reshape(4, 5)
print(arr10)

print(arr10[3])
print(arr10[3][1])
print(arr10[3, 1])
print(arr10[0:3, 2:])

arr11 = arr9.reshape(2, 2, 5)
print(arr11)

print(arr11[1, 0, 3])

[[9 6 7 0 5]
 [6 3 3 1 5]
 [0 3 5 8 1]
 [3 6 9 9 4]]
[3 6 9 9 4]
6
6
[[7 0 5]
 [3 1 5]
 [5 8 1]]
[[[9 6 7 0 5]
  [6 3 3 1 5]]

 [[0 3 5 8 1]
  [3 6 9 9 4]]]
8


In [11]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
print(len(names))
print(type(names))

mask = (names == 'Joe')
print(mask)
print(type(mask))

dat = randn(7, 4)
print(dat)
print(dat[mask])
print(type(dat[mask]))

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
7
<class 'numpy.ndarray'>
[False  True False False False  True  True]
<class 'numpy.ndarray'>
[[ 0.35315729 -1.06819354  0.65026699 -0.60616072]
 [ 1.45870046 -0.09135071 -0.24635557 -0.954733  ]
 [ 0.63372366  0.23544665 -1.36485954  1.39764218]
 [-0.99522806 -0.71380676  0.71740036 -0.52913533]
 [-1.58612468 -0.79947465  1.25614089  1.20372138]
 [ 1.39838745  0.15158837 -0.75191843  0.86543523]
 [-1.25330993 -2.14629154 -2.40895168 -2.55402753]]
[[ 1.45870046 -0.09135071 -0.24635557 -0.954733  ]
 [ 1.39838745  0.15158837 -0.75191843  0.86543523]
 [-1.25330993 -2.14629154 -2.40895168 -2.55402753]]
<class 'numpy.ndarray'>
