In [2]:
import tensorflow as tf

In [3]:
three = tf.constant(3.)

with tf.Session() as sess:
    print(sess.run(three))

3.0


In [4]:
matrix1 = tf.constant([[3., 3.]])

matrix2 = tf.constant([[2.], [2.]])

product = tf.matmul(matrix1, matrix2)

with tf.Session() as sess:
    print(sess.run(product))


[[ 12.]]


In [0]:
import numpy as np

arr0 = [1, 3, 5]
arr1 = np.array([1, 3, 5])
arr1_1 = np.array(arr0)
print(type(arr0))
print(type(arr1))
print(type(arr1_1))

In [29]:
arr2 = np.arange(20)
print(arr2)

arr3 = arr2.reshape(4, 5)
print(arr3)
print(arr3.shape)
print(arr2.shape)
print(arr3.ndim)
print(arr2.ndim)

arr4 = np.random.randint(10, size=6)
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(20,)
2
1
[9 4 5 4 2 7]


In [27]:
from numpy.random import randint

arr5 = randint(10, size=(3, 5))
print(arr5)

print(arr5 * 3)
print(arr5 + 1)

arr6 = randint(10, size=(3, 5))
print(arr6)

print(arr5 + arr6)
print(arr5 * arr6)


def sq(x):
    return(x * x)

print(arr5)
print(sq(arr5))

[[8 7 4 7 3]
 [5 2 0 7 2]
 [9 5 6 3 3]]
[[24 21 12 21  9]
 [15  6  0 21  6]
 [27 15 18  9  9]]
[[ 9  8  5  8  4]
 [ 6  3  1  8  3]
 [10  6  7  4  4]]
[[4 2 8 4 5]
 [3 7 9 2 7]
 [6 8 5 1 6]]
[[12  9 12 11  8]
 [ 8  9  9  9  9]
 [15 13 11  4  9]]
[[32 14 32 28 15]
 [15 14  0 14 14]
 [54 40 30  3 18]]
[[8 7 4 7 3]
 [5 2 0 7 2]
 [9 5 6 3 3]]
[[64 49 16 49  9]
 [25  4  0 49  4]
 [81 25 36  9  9]]


In [37]:
print(np.random.randn(10))

from numpy.random import randn

arr7 = randn(5)
print(arr7)

arr8 = randint(10, size=5)
print(arr8)

print(arr7.dtype)
print(arr8.dtype)

[-0.94022071 -0.28547594 -1.05024582 -1.10577844  2.45269578 -0.24037681
  1.11364595 -0.17346229  1.02361108  0.60436116]
[ 0.60928977  0.82537302 -0.40238168  1.68018668 -0.1070007 ]
[1 8 4 1 9]
float64
int64


In [33]:
print(np.zeros(10))
print(np.zeros((3, 5)))
print(np.ones(10))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [38]:
arr9 = randint(10, size=20)
print(arr9)

print(arr9[0])
print(arr9[3])
print(arr9[1:5])
print(arr9[1:])
print(arr9[:])

[6 8 4 9 8 2 0 5 6 2 4 0 0 8 7 4 4 6 8 9]
6
9
[8 4 9 8]
[8 4 9 8 2 0 5 6 2 4 0 0 8 7 4 4 6 8 9]
[6 8 4 9 8 2 0 5 6 2 4 0 0 8 7 4 4 6 8 9]


In [42]:
arr10 = arr9.reshape(4, 5)
print(arr10)

print(arr10[3])
print(arr10[3][1])
print(arr10[3, 1])
print(arr10[0:3, 2:])

arr11 = arr9.reshape(2, 2, 5)
print(arr11)

print(arr11[1, 0, 3])

[[6 8 4 9 8]
 [2 0 5 6 2]
 [4 0 0 8 7]
 [4 4 6 8 9]]
[4 4 6 8 9]
4
4
[[4 9 8]
 [5 6 2]
 [0 8 7]]
[[[6 8 4 9 8]
  [2 0 5 6 2]]

 [[4 0 0 8 7]
  [4 4 6 8 9]]]
8


In [22]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
print(len(names))
print(type(names))

mask = (names == 'Joe')
print(mask)
print(type(mask))

dat = randn(7, 4)
print(dat)
print(dat[mask])
print(type(dat[mask]))

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
7
<class 'numpy.ndarray'>
[False  True False False False  True  True]
<class 'numpy.ndarray'>
[[-0.801918   -1.10092773 -0.6696535  -0.14943817]
 [ 1.26001898  0.080592    1.7666345   0.2821165 ]
 [ 1.01424385  0.78670096 -1.53048732 -1.22931663]
 [ 0.11735186  0.3905679   0.71485113 -0.06382837]
 [-0.80671771  1.94831584  0.54022823  0.53876368]
 [ 1.75329664  0.1059435  -0.20442817 -0.35098416]
 [-0.68051927 -1.12532593 -0.69272926 -0.69538292]]
[[ 1.26001898  0.080592    1.7666345   0.2821165 ]
 [ 1.75329664  0.1059435  -0.20442817 -0.35098416]
 [-0.68051927 -1.12532593 -0.69272926 -0.69538292]]
<class 'numpy.ndarray'>
